name: Sitewatcher

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '23 6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Setup Geckodriver
      uses: browser-actions/setup-geckodriver@v0.0.0
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set up sitewatcher
      run: python -m pip install -e .
    - name: Watch site
      run: |
        python sitewatcher/watcher.py
